zynqmp: Fix printf conversion specifier
Building with a high log level generates the below warning (error
with -Werror) due to an incorrect printf conversion.
  plat/xilinx/zynqmp/pm_service/pm_svc_main.c: In function 'pm_smc_handler':
  plat/xilinx/zynqmp/pm_service/pm_svc_main.c:180:3: error: format '%d' expects argument of type 'int', but argument 2 has type 'uint64_t' [-Werror=format=]
     VERBOSE("Initialize pm callback, irq: %d\n", x1);
     ^

Fixes: 58260e843fec4 "zynqmp pm_service: Added ipi_fiq_handler and
       callback mechanism"

Signed-off-by: Soren Brinkmann <soren.brinkmann@xilinx.com>